version: '3.8'

services:
  mongodb:
    image: mongo:7.0.31
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: seb
      MONGO_INITDB_ROOT_PASSWORD: x_x&xK+gN6V/u9A1234
    volumes:
      - mongodb_data:/data/db
    networks:
      - abbaye11


volumes:
  mongodb_data:
    driver: local

networks:
  abbaye11:
    name: abbaye11
    external: true